Class {
	#name : 'HeraNoReporter',
	#superclass : 'HeraReporter',
	#category : 'Hera-Reporting',
	#package : 'Hera',
	#tag : 'Reporting'
}

{ #category : 'reporting' }
HeraNoReporter >> reportAfterScenarioHookError: anError [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportBeforeScenarioHookError: anError [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportEndOfBackground: aBackground [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportEndOfBackgroundStep: aStep [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportEndOfFeature: aFeature [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportEndOfRule: aRule [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportEndOfScenario: aScenario [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportEndOfStep: aStep [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportErrorStep: aStep of: aScenario withError: anError [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportFailedStep: aStep of: aScenario withFailure: aFailure [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportPassedStep: aStep [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportResult: result [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportStartOfBackground: aBackground [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportStartOfBackgroundStep: aStep [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportStartOfFeature: aFeature [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportStartOfRule: aRule [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportStartOfScenario: aScenario [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportStartOfStep: aStep [

	"Do nothing."
]

{ #category : 'reporting' }
HeraNoReporter >> reportSuppressed [

	"Do nothing."
]
