name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "5 0 * * 1" # At 00:05 on Monday.

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [Pharo64-13, Pharo64-alpha]
    name: ${{ matrix.smalltalk }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SmalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        timeout-minutes: 10
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: ${{ matrix.smalltalk }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Results of acceptance tests ${{ matrix.smalltalk }}
          path: ${{ env.SMALLTALK_CI_BUILD }}/acceptance_test_results.txt
