name: smalltalkCI

on:
  push:
  pull_request:
  schedule:
    - cron: "5 0 * * 1" # At 00:05 on Monday.

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-stable , Pharo64-13 , Pharo64-alpha ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v4
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        timeout-minutes: 10
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: ${{ matrix.smalltalk }}
          token: ${{ secrets.CODECOV_TOKEN }}
